### ISSUE TITLE
Windows executable does not work in powershell or command prompt

### ISSUE THREAD

**Issue by zaesur** [Shuumatsu/racket-pretty-printer#2]
On windows, the executable produced by stack won't run in powershell or command prompt (although it works in git bash). This breaks the vscode extension, as stdout of spawnSync will be empty, which results in erasing all text.

The problem seems to be that stack doesn't include a certain .dll:

![image](https://user-images.githubusercontent.com/26276287/98469132-2ad52480-21de-11eb-8f58-2e93b153fe16.png)

I'm not sure how to fix this, as I'm not so familiar with haskell or its build tools.

**Comment by zaesur** [comment]
[This article shows a workaround](https://docs.haskellstack.org/en/v1.2.0/faq/#how-to-get-a-working-executable-on-windows).

Adding `%USERPROFILE%\AppData\Local\Programs/stack/i386-windows/ghc-8.6.5/mingw/bin` to the path has solved the issue for me.

**Comment by Shuumatsu** [comment]
> [This article shows a workaround](https://docs.haskellstack.org/en/v1.2.0/faq/#how-to-get-a-working-executable-on-windows).
> 
> Adding `%USERPROFILE%\AppData\Local\Programs/stack/i386-windows/ghc-8.6.5/mingw/bin` to the path has solved the issue for me.

This extension replaces the text with the stdout of racket-pretty-printer. 

can you try these commands to make sure it works.
```
racket-pretty-printer on  master [✘?]
❯ racket-pretty-printer -f .\demo.rkt
(define a 2)

(multiple-value-bind (a b) (gethash 'a *m*) (list a b))

racket-pretty-printer on  master [✘?]
❯ cat .\demo.rkt | racket-pretty-printer --stdin
(define a 2)

(multiple-value-bind (a b) (gethash 'a *m*) (list a b))
```

**Comment by zaesur** [comment]
It took a long time to debug the issue, but in the end it turned out to be a problem with the way Haskell works on windows.

If anyone else stumbles upon this issue, they can resolve things by adding the missing dll to their path, as described in my previous comment.
